# Generated by Django 3.0.2 on 2020-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='contact2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='연락처2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='연락처2'),
        ),
    ]
